### ISSUE TITLE
Add test setup

### ISSUE THREAD

**Issue by bittner** [Orange-Cyberdefense/arsenal#32]
Arsenal has stopped working on my machine since I pulled the latest changes from GitHub today.

It may be worth to add a test suite that verifies that the Python code keeps working. Would you accept a related PR?

If yes, which Python versions do you want to support? Is Python 3.6+ sufficient, or should Python 2.7 ideally be included?

**Comment by Mayfly277** [comment]
"Arsenal has stopped working on my machine since I pulled the latest changes from GitHub today." 
I am sorry to hear that, could you tell me what is the error ? if you use the github clone version and not the pip install, did you install all the requirements ?

As python2 is dead, we want to support python 3.6+

**Comment by bittner** [comment]
The error occurred when I ran Arsenal as a module, i.e. `python -m arsenal`. I opened #33 to fix the issue.

I believe, adding a test setup and start developing a test suite would still make sense.

**Comment by Mayfly277** [comment]
thx for the PR ! i close the issue ;)
